services:
  mongodb:
    image: mongo
    container_name: devora-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: devora
      MONGO_INITDB_ROOT_PASSWORD: devora_local_pw
    volumes:
      - devora-mongo-data:/data/db

volumes:
  devora-mongo-data:
